#ifndef PPG_IBI_CONFIG_H
#define PPG_IBI_CONFIG_H

#define PPG_IBI_CHANNEL_COUNT (4u)
#define PPG_IBI_SAMPLE_RATE_HZ (50u)
#define PPG_IBI_SAMPLE_PERIOD_MS (20u)
#define PPG_IBI_ADC_BITS (24u)
#define PPG_IBI_TIMESTAMP_TOLERANCE_MS (2u)
#define PPG_IBI_RAM_BUDGET_BYTES (20480u)
#define PPG_IBI_SELECTED_CHANNEL_NONE (255u)

#endif /* PPG_IBI_CONFIG_H */
